version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./src:/var/www/html
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    environment:
      PHP_IDE_CONFIG: "serverName=whatever"
    volumes:
      - ./src:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini